<html>
<head>
<style>
.img{
    padding-left: 30px;
}
.carousel-inner{
   
    margin-bottom: 18px;

}
</style>

</head>
<body>
<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>
<?php echo "Welcome to ShopZone" ?>
 </center></h1>
 </div>
<table class="table table-striped table-bordered">
    <div class="row">
  <div class="col-md-8"><th>ShopZone</th></div>
  
  
 

</div>



<tr>
<td> <a  href='/index/list-category'> Departments </a></td>
</tr>

</table>


</div>



<?php foreach ($this->select_image as $key => $value) {?>

<div id="carousel-example-generic" " class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox" class= "slider" >
    <div class="item active">
      <img src=<?=$value['image']?> alt="<?php$value['url']?>">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="<?=$value['image']?>" alt="<?php$value['url']?>">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
   <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
 
</div>
 <?php }?>



   
<div class="row">
<?php 
foreach ($this->rate_product as $key => $value) {?>


  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
     <img class="img" src=<?=$value['picture']?> alt=<?=$value['name']?>>
      <div class="caption">
        <h3>Hight Product</h3>
        <p><?=$value['description'] ?></p>
        <p><?=$value['price'] ?></p>
        <p><a href="#" class="btn btn-primary" role="button">Add to Cart</a> <a href="#" class="btn btn-default" role="button">Add to Wish List</a></p>
      </div>
    </div>
  </div>

<?php
}
?>
</div>



</body>

</html>

<!-- 
  echo "<tr>
  <td>".$value['name']."</td><td>".$value['description'].$value['price'].$value['quantity']."<img src=".$value['picture'].">"."</td>".
"<td> <a class='btn btn-primary' href='/index/details-Product/uid/".$value['id']."'> QuickLook </a></td>"
."</tr>";
}

foreach ($this->select_image as $key => $value) {

  echo "<tr>
  <td>"."<img src=".$value['image'].">"."</td>".
"<td> <a class='btn btn-primary' href='/index/details-Product/uid/".$value['url']."'> QuickLook </a></td>"
."</tr>";

}

?> -->