<div class="col-md-9 w_content">
		
		<!-- grids_of_4 -->
		<div class="grids_of_4">
		<?php
			foreach ($this->product as $key => $value) { 


 ?>
			  <div class="grid1_of_4">
					<div class="content_box"><a href="<?='/index/details-Product/uid/'.$value['id'] ?>">
				   	   	 <img src="<?php  echo "/".$value['picture'];?>" class="img-responsive" alt="" />
					   	  </a>
					     
					   	  <?php if($this->languge=="En") {?>
					    <h4><a href="details.html"> <?php $value['name'];?></a></h4>
					     <p> <?php $value['description'];?></p>
					     <?php} else if($this->languge->type=="Ar"){ ?>
					     <h4><a href="details.html"> <?php  $value['ar_name'];?></a></h4>
					      <p> <?php  $value['description_ar'];?></p>
					      <?php } ?>
						 

						 <div class="grid_1 simpleCart_shelfItem">
					    
						 <div class="item_add"><span class="item_price"><h6><?php echo $value['price'];?></h6></span></div>
						<div class="item_add"><span class="item_price"><a href="<?='/user/inserwishlist/uid/'.$value['id'] ?> ">ADD to wish list</a></span></div>
						 </div>
				   	</div>
				</div>
				
							   	<?php }?>

		
			
			<div class="clearfix"></div>
		</div>
		<!-- end grids_of_4 -->
