
<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
  <center>
  	<h1> Login</h1>
  </center>
  </div>
   <div class="panel-body">
   <?php echo $this->loginform_var;?>
   <?php echo '<a  class="btn btn-primary" href="' . htmlspecialchars( $this->facebookUrl) . '"> Log in
with Facebook! </a>'; ?>  
       
       
       <meta name="google-signin-client_id" content="681093495489-er5i9j0lu0ood3jb2u6qairgcselmaf4.apps.googleusercontent.com">
        <div class="g-signin2" data-onsuccess="onSignIn"></div>
	<script src="https://apis.google.com/js/platform.js" async defer>
	</script>
         
   </div>
   </div>
   </div>