<?php
//$usersNs = new Zend_Session_NameSpace("members");
//              $usersNs->userType = $sessionDataObj->type;
//               print_r($_SESSION);
//////                die();
////                $path = "/".$sessionDataObj->type;
////                $this->redirect($path);
$usersNs = new Zend_Session_NameSpace("members");
       
        
foreach ($this->indexSearch as $key => $value){
    ?>
      <div class="search-list-item-name">
          
          <a href="<?='/index/details-Product/uid/'.$value['id']?>">     <?php
    echo $value['name'];
    ?></a>
           </div>
          <?php
}
?>
