<!DOCTYPE html>
<html>
	<head>

		<meta charset="utf-8">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>   
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

	</head>
        <body>
<?php
$auth=Zend_Auth::getInstance();
    $storage=$auth->getStorage();
    $userdata=$storage->read();
    $fbsession = new Zend_Session_Namespace('facebook');

    if(!empty($userdata)|| !empty($fbsession->name))
    {
        if (!empty($fbsession->name)){
          echo 'Welcome' . $fbsession->name;
        }else{
      // if authenticated and logged in 
    echo 'Welcome' . $userdata->name;
  }
    echo' <a href="/user/logout">Logout</a>';
  }

  else
  {// if not logged in 
    echo' <a href="/user/login">Login</a>';
  }



?>
<?php echo $this->layout()->content; ?>

        </body>
</html>