<!DOCTYPE html>
<html>
	<head>

		<meta charset="utf-8">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		 
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<title></title>
    <link rel="stylesheet" href="style.css">
    
      
<!--//           headTitle() . PHP_EOL;
//           echo $this->jQuery() . PHP_EOL; 
//           
//    -->
	</head>
        <body>
<?php
$auth=Zend_Auth::getInstance();
    $storage=$auth->getStorage();
    $userdata=$storage->read();
    $fbsession = new Zend_Session_Namespace('facebook');

    if(!empty($userdata)|| !empty($fbsession->name))
    {
        if (!empty($fbsession->name)){
          echo 'Welcome' . $fbsession->name;
        }else{
      // if authenticated and logged in 
    echo 'Welcome' . $userdata->name;
  }
    echo' <a href="/user/logout">Logout</a>';
  }

  else
  {// if not logged in 
    echo' <a href="/user/login">Login</a>';
  }



?>
<?php echo $this->layout()->content; ?>

        </body>
</html>