<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center><?php

echo $this->product_data['name']."<br>"."Quanyity: ".$this->product_data['quantity'];

     ?></center></h1>
  </div>
  <div class="panel-body">
<form method="POST" action="/user/addtocart">
<?php echo $this->product_data['description']."<br>".
"<img src="."\""."/".$this->product_data['picture']."\""."alt='product pic' height='42' width='42'>"."<br>".
"price: ".$this->product_data['price']."<br>".
"quantity: <input type='number' name='quantity' min='1' max=".$this->product_data['quantity']."><br>".
"<input type='hidden' name='product' value=".$this->product_data['id'].">".
"<input type='hidden' name='custid' value=".$this->product_data['customer_id'].">".
"rate: ".$this->product_data['rates_avg']."<br>".
"discount: ".$this->product_data['offer']."<br>".
"<button type='submit' class='btn btn-primary'>Add to Cart</button>"; ?>
</form>
  </div>
</div>

</div>
