<html>
<head>


	<meta name="google-signin-client_id" content="749856596970-cp4j6pas08c73q613df6g2vs9dro259e.apps.googleusercontent.com">

	<script src="https://apis.google.com/js/platform.js" async defer>
	</script>
	<script>
	function onSignIn(googleUser) {
		var profile = googleUser.getBasicProfile();
		console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
		console.log('Name: ' + profile.getName());
		console.log('Image URL: ' + profile.getImageUrl());
		console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
		}
		window.location="savedata.php?id="+profile.getId()+"&name="+profile.getName()+"&img"+profile.getImageUrl()+"&email"+profile.getEmail();
	</script>
</head>
<body>
	<div class="g-signin2" data-onsuccess="onSignIn"></div>
</body>
</html>
