<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>
<?php echo "Product-List" ?>
 </center></h1>
 </div>
<table class="table table-striped table-bordered">

  <div ><th>Name of Product</th><th>description</th><th>price</th><th>qunatity</th></div>




</div>


<?php
foreach ($this->product as $key => $value) {

  echo "<tr>
  <td>".$value['name']."</td><td>".$value['description'].$value['price'].$value['quantity']."</td>".
"<td> <a class='btn btn-primary' href='/user/detailsproduct/uid/".$value['id']."'> QuickLook </a></td>"
."</tr>";
}
 ?>

</table>
