<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<style>
@import url(http://fonts.googleapis.com/css?family=Roboto:500,100,300,700,400);

* {
  margin: 0;
  padding: 0;
  font-family: roboto;
}


.cont {
  width: 93%;
  max-width: 350px;
  text-align: center;
  margin: 4% auto;
  padding: 0px ;
  padding-bottom: 60px;
  background: #FFFFF;
  color: #EEE;
  border-radius: 5px;
  border: thin solid #444;
  overflow: hidden;
  height: 20px
}

hr {
  margin: 20px;
  border: none;
  border-bottom: thin solid rgba(255,255,255,.1);
}

div.title { font-size: 2em; }

h1 span {
  font-weight: 300;
  color: #Fd4;
}

div.stars {
  width: 270px;
  display: inline-block;
}

input.star { display: none; }

label.star {
  float: right;
  padding: 10px;
  font-size: 36px;
  color: #444;
  transition: all .2s;
}

input.star:checked ~ label.star:before {
  content: '\f005';
  color: #FD4;
  transition: all .25s;
}

input.star-5:checked ~ label.star:before {
  color: #FE7;
  text-shadow: 0 0 20px #952;
}

input.star-1:checked ~ label.star:before { color: #F62; }

label.star:hover { transform: rotate(-15deg) scale(1.3); }

label.star:before {
  content: '\f006';
  font-family: FontAwesome;
}
</style>
<link href="http://www.cssscript.com/wp-includes/css/sticky.css" rel="stylesheet" type="text/css">



<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>
<?php echo "Product-List" ?>
 </center></h1>
 </div>
<table class="table table-striped table-bordered">

  <div ><th>Name of Product</th><th>description</th><th>price</th><th>quantity</th></div>




</div>


<?php
foreach ($this->product as $key => $value) { ?>

    <tr>  
  <td><?=$value['name']?></td>
  <td><?=$value['description']?></td>
  <td><?=$value['price']?></td>
  <td><?=$value['quantity']?></td>
   <td> <a class='btn btn-primary' href='/user/detailsproduct/uid/<?=$value['id']?>' > Quick Look </a></td>
   <td>
            <div class="cont">
  <div class="stars">
      <?php
      $value['rates_avg'] = round($value['rates_avg']);
      if ($value['rates_avg'] == 5)
      {
      ?>    
      
      <form method="post" action="/user/listproduct">
          <input class="star star-5" id=<?="star".$value['id']."5" ?> type="radio" name="star" value="5" checked onclick="submit()"/>
      <label class="star star-5" for=<?="star".$value['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$value['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$value['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$value['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$value['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$value['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$value['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$value['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$value['id']."1" ?>></label>
      <input type="text" value=<?=$value['id']?> name="product" style="display:none"/>
      <input type="text" value=<?=$value['id']?> name="customer" style="display:none"/>
    </form>
      <?php }
      else if($value['rates_avg'] == 4){
                ?>
      <form method="post" action="/user/listproduct">
          <input class="star star-5" id=<?="star".$value['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$value['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$value['id']."4" ?> type="radio" name="star" value="4" checked onclick="submit()"/>
      <label class="star star-4" for=<?="star".$value['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$value['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$value['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$value['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$value['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$value['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$value['id']."1" ?>></label>
      <input type="text" value=<?=$value['id']?> name="product" style="display:none"/>
      <input type="text" value=<?=$value['id']?> name="customer" style="display:none"/>
    </form>
      
      
      <?php 
      }
      else if($value['rates_avg'] == 3){
                ?>
      <form method="post" action="/user/listproduct">
          <input class="star star-5" id=<?="star".$value['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$value['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$value['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$value['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$value['id']."3" ?> type="radio" name="star" value="3" checked onclick="submit()"/>
      <label class="star star-3" for=<?="star".$value['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$value['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$value['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$value['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$value['id']."1" ?>></label>
      <input type="text" value=<?=$value['id']?> name="product" style="display:none"/>
      <input type="text" value=<?=$value['id']?> name="customer" style="display:none"/>
    </form>
      
      
      
      <?php }
      else if($value['rates_avg'] == 2){
                ?>
      <form method="post" action="/user/listproduct">
          <input class="star star-5" id=<?="star".$value['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$value['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$value['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$value['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$value['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$value['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$value['id']."2" ?> type="radio" name="star" value="2" checked onclick="submit()"/>
      <label class="star star-2" for=<?="star".$value['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$value['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$value['id']."1" ?>></label>
      <input type="text" value=<?=$value['id']?> name="product" style="display:none"/>
      <input type="text" value=<?=$value['id']?> name="customer" style="display:none"/>
    </form>
     
      
      
      <?php }
      else if($value['rates_avg'] == 1){
                ?>
      <form method="post" action="/user/listproduct">
          <input class="star star-5" id=<?="star".$value['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$value['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$value['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$value['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$value['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$value['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$value['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$value['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$value['id']."1" ?> type="radio" name="star" value="1" checked onclick="submit()" />
      <label class="star star-1" for=<?="star".$value['id']."1" ?>></label>
      <input type="text" value=<?=$value['id']?> name="product" style="display:none"/>
      <input type="text" value=<?=$value['id']?> name="customer" style="display:none"/>
    </form>
      
      
      
      <?php }
      else {
                ?>
      <form method="post" action="/user/listproduct">
          <input class="star star-5" id=<?="star".$value['id']."5" ?> type="radio" name="star" value="5"  onclick="submit()"/>
      <label class="star star-5" for=<?="star".$value['id']."5" ?>></label>
      <input class="star star-4" id=<?="star".$value['id']."4" ?> type="radio" name="star" value="4"  onclick="submit()"/>
      <label class="star star-4" for=<?="star".$value['id']."4" ?>></label>
      <input class="star star-3" id=<?="star".$value['id']."3" ?> type="radio" name="star" value="3" onclick="submit()"/>
      <label class="star star-3" for=<?="star".$value['id']."3" ?>></label>
       <input class="star star-3" id=<?="star".$value['id']."2" ?> type="radio" name="star" value="2" onclick="submit()"/>
      <label class="star star-2" for=<?="star".$value['id']."2" ?>></label>
      <input class="star star-1" id=<?="star".$value['id']."1" ?> type="radio" name="star" value="1" onclick="submit()" />
      <label class="star star-1" for=<?="star".$value['id']."1" ?>></label>
      <input type="text" value=<?=$value['id']?> name="product" style="display:none"/>
      <input type="text" value=<?=$value['id']?> name="customer" style="display:none"/>
    </form>
      <?php } ?>
      
      
  </div>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46156385-1', 'cssscript.com');
  ga('send', 'pageview');

</script>

            
            
            
            
        </td>

  </tr>
    
    <?php
}
 ?>

</table>
