<div class="container">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1><center>
<?php echo "Wish-List" ?>
 </center></h1>
 </div>
<table class="table table-striped table-bordered">
	
  <div ><th>Your Name</th><th>product</th></div>
 
  
 

</div>


<?php
foreach ($this->model as $key => $value) {

  echo "<tr>
  <td>".$value['customer_name']."</td><td>".$value['product_name']."</td>".
"<td> <a class='btn btn-primary' href='/user/delwishlist/wid/".$value['id']."'> Remove </a></td>"."</tr>";
}
 ?>

</table>