<table class="table">
<thead>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Email</th>
    <th>Type</th>
    <th>is_active</th>
    
    <th>Actions</th>
  </tr>
</thead>
<tbody>

              <?php





    foreach($this->users as $key => $value)
    {
            ?>
    <tr>
        
        <td> <?= $value['id'] ?> </td>
        <td><?= $value['name'] ?></td>
        <td><?= $value['email'] ?></td>
        <td><?= $value['type'] ?></td>
        <td><?= $value['is_active'] ?></td>
        
            
        <td> <a href="<?= 'productdetails/pid/'.$value['id'] ?>" ><button class="btn btn-primary"  type="button" name="button"> Details </button></a> </td>
        <td>  <a  href="<?= 'editproduct/pid/'.$value['id'] ?>"><button class="btn btn-default" type="button" name="button"> edit  </button></a> </td>
        <td>  <a  href="<?= 'deleteproduct/pid/'.$value['id'] ?>"><button class="btn btn-danger" type="button" name="button"> Delete  </button></a> </td>    
        
        
        
        
			    </tr>
			    <?php } ?>
			  </tbody>


		</table>
		